### PR TITLE
Adding tray icon

### LINKED ISSUE #4: Add Play/Pause buttons to system tray icon

### LINKED ISSUE #5: Add system tray icon

### PR DESCRIPTION
**Pull request by lesthack**
Fixes #4 
Fixes #5 

Issue: Add system tray icon #5

### CODE REVIEW

**Comment by felicianotech** [comment]
Tried to test but it looks like the web app is under maintenance right now. I'll check back soon.

**Comment by AppelonD** [comment]
It works for me, but the point of a tray icon is the option to minimize to tray, I only see quit when I click it ?? (Running Fedora 30, gnome-shell)

**Comment by lesthack** [comment]
@AppelonD You're right. The new commit adds this feature.

**Comment by AppelonD** [comment]
Thanks @lesthack It works great :-) I have dreamed of this for a long time Thanks :dancer:

**Comment by felicianotech** [comment]
When I tried testing before and Pocket Casts was down, it looks like that was due to their major update that recently came out.

I tested and this looks good. Thank you @lesthack.

Snap users will be automatically updated at some point soon. `.deb` users will need to download the v0.3.0 release once it's available here on GitHub within an hour.

**Pull request merged**
